INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Comissao de Alimentacao');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Comissao de Alojamento');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Comissao de Divulgacao');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Comissao de Estudos/Arte');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Comissao de Multimeios');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Comissao de Pequenos Companheiros');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Comissao de Recepcao');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Comissao de Servicos Gerais');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Comissao Medica, Atend. Fraterno e Passe');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Coordenacao Geral/Espelho da area Administrativa');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Coordenacao Geral/Espelho da area de Apoio Logistico');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Coordenacao Geral/Espelho da area de Estudos Doutrinarios');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Coordenacao Geral/Espelho de area de Assist. Medica e Atend. Fraterno');

INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Colheita');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Flores');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Pequenos Companheiros');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Polem');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Sementes');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Tarefeiro');
INSERT INTO `comeerj`.`Equipe` (`nome`)VALUES('Tarefeiros do Bem');
